spring:
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    openshift:
      zipkin:
        discovery:
          serviceName: zipkin
cxf:
 path: /api
 jaxrs:
  component-scan: true